apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpmetrics-deployment
spec:
  selector:
    matchLabels:
      app: httpmetrics
  replicas: 1
  template:
    metadata:
      labels:
        app: httpmetrics
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: httpmetrics
          image: srikantsarwa/apipromexp:v1
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: httpmetrics-service
  labels:
    app: httpmetrics-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
  selector:
    app: httpmetrics